/*
 * ULTRASONIC_types.h
 *
 *  Created on: Mar 2, 2023
 *      Author: m_hsa
 */

#ifndef ULTRASONIC_TYPES_H_
#define ULTRASONIC_TYPES_H_

typedef enum{
	ULTRASONIC_PA0 = 10,
	ULTRASONIC_PA1 ,
	ULTRASONIC_PA2 ,
	ULTRASONIC_PA3 ,
	ULTRASONIC_PA4 ,
	ULTRASONIC_PA5 ,
	ULTRASONIC_PA6 ,
	ULTRASONIC_PA7 ,
	ULTRASONIC_PB0 = 20,
	ULTRASONIC_PB1 ,
	ULTRASONIC_PB2 ,
	ULTRASONIC_PB3 ,
	ULTRASONIC_PB4 ,
	ULTRASONIC_PB5 ,
	ULTRASONIC_PB6 ,
	ULTRASONIC_PB7 ,
	ULTRASONIC_PC0 = 30,
	ULTRASONIC_PC1 ,
	ULTRASONIC_PC2 ,
	ULTRASONIC_PC3 ,
	ULTRASONIC_PC4 ,
	ULTRASONIC_PC5 ,
	ULTRASONIC_PC6 ,
	ULTRASONIC_PC7 ,
	ULTRASONIC_PD0 = 40,
	ULTRASONIC_PD1 ,
	ULTRASONIC_PD2 ,
	ULTRASONIC_PD3 ,
	ULTRASONIC_PD4 ,
	ULTRASONIC_PD5 ,
	ULTRASONIC_PD6 ,
	ULTRASONIC_PD7

}Ultrasonic_PinType; // channel means pin

#endif /* ULTRASONIC_TYPES_H_ */
